export default  {
  SELECTOR_GAME_TYPE: '#game-type',
  SELECTOR_FORM_OPTIONS: '#form-options',
  SELECTOR_ROW_NUM_CONTAINER: '#row-num-container',
  SELECTOR_ROW_NUM: '#row-num',
  SELECTOR_BOARD: '.board',
  SELECTOR_BOX: '.box',
  SELECTOR_PLAYER_1_SCORE: '#p1-score',
  SELECTOR_PLAYER_2_SCORE: '#p2-score',
  SELECTOR_NEXT_NAME: '#p-name',
  SELECTOR_NEXT_MARKER: '#p-marker',
  SELECTOR_NEW_GAME: '#new-game',
  SELECTOR_TOTAL_GAMES: '#total-games',
  SELECTOR_RESET_ALL: '#reset-all',
  SELECTOR_NEXT_UP: '#next-up',
  GAME_TYPE_DEFAULT: 'default',
  GAME_TYPE_RANDOM: 'random',
  GAME_TYPE_N_IN_A_ROW: 'n-in-a-row',
  DEFAULT_ROW_NUM: 3,
  BOARD_PADDING: '8',
  PLAYER_1: 'p1',
  PLAYER_2: 'p2',
  CONTEXT_ROW: 'row',
  CONTEXT_COLUMN: 'column',
  CONTEXT_DIAGONAL: 'diagonal',
  DISPLAY_LOSING_BOX_BACKGROUND: '#ccc',
  DISPLAY_LOSING_BOX_COLOR: '#eee'
};